name: Python Data Analysis CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest python-dotenv numpy scipy matplotlib seaborn

      - name: Create plots folder
        run: mkdir -p plots

      - name: Run analysis script
        run: python test_feedback_ci.py

      - name: Upload generated plots
        uses: actions/upload-artifact@v4
        with:
          name: plots
          path: plots/
